"""XDG / desktop-environment cache providers.

All of these are classic, regenerable caches living under ``$XDG_CACHE_HOME``.
Trash is deliberately NOT handled here: it can contain user files, so it is
out of scope for a *cache* cleaner (documented design decision, rule 5.2).
"""

from __future__ import annotations

import os

from ..core.provider import CachePath, CacheProvider, Category
from ..core.safety import SafetyLevel

__all__ = [
    "ThumbnailsProvider", "FontconfigProvider", "MesaShaderCacheProvider",
    "KdeSycocaProvider",
]


class ThumbnailsProvider(CacheProvider):
    id = "xdg.thumbnails"
    name = "Thumbnails"
    category = Category.DESKTOP
    safety = SafetyLevel.SAFE_CACHE

    def detect(self) -> bool:
        return os.path.isdir(os.path.join(self.ctx.xdg_cache, "thumbnails"))

    def cache_paths(self) -> list[CachePath]:
        return [CachePath(
            os.path.join(self.ctx.xdg_cache, "thumbnails"),
            "Image/video thumbnail previews (file managers rebuild them on demand)",
            SafetyLevel.SAFE_CACHE,
        )]

    def explain(self) -> str:
        return ("Deletes cached image and video previews generated by file managers "
                "and galleries. They are recreated automatically; the only cost is a "
                "brief delay the next time a folder with media is opened.")


class FontconfigProvider(CacheProvider):
    id = "xdg.fontconfig"
    name = "Font cache (fontconfig)"
    category = Category.DESKTOP
    safety = SafetyLevel.SAFE_CACHE

    def detect(self) -> bool:
        return os.path.isdir(os.path.join(self.ctx.xdg_cache, "fontconfig"))

    def cache_paths(self) -> list[CachePath]:
        return [CachePath(
            os.path.join(self.ctx.xdg_cache, "fontconfig"),
            "Font metadata cache (rebuilt by fc-cache)",
            SafetyLevel.SAFE_CACHE,
        )]

    def explain(self) -> str:
        return ("Deletes the fontconfig font-metadata cache. It is rebuilt "
                "automatically (fc-cache); applications may take slightly longer "
                "to start once afterwards.")


class MesaShaderCacheProvider(CacheProvider):
    id = "xdg.mesa-shaders"
    name = "Mesa / GPU shader cache"
    category = Category.DESKTOP
    safety = SafetyLevel.SAFE_CACHE

    def detect(self) -> bool:
        c = self.ctx.xdg_cache
        return any(os.path.isdir(os.path.join(c, d))
                   for d in ("mesa_shader_cache", "mesa_shader_cache_db", "nv"))

    def cache_paths(self) -> list[CachePath]:
        c = self.ctx.xdg_cache
        paths = []
        for d, purpose in (
            ("mesa_shader_cache", "Mesa GLSL shader cache"),
            ("mesa_shader_cache_db", "Mesa shader cache database"),
            ("nv", "NVIDIA proprietary shader cache"),
        ):
            p = os.path.join(c, d)
            if os.path.isdir(p):
                paths.append(CachePath(p, purpose, SafetyLevel.SAFE_CACHE))
        return paths

    def explain(self) -> str:
        return ("Deletes compiled GPU shader caches. Games and GPU applications "
                "recompile shaders on next launch (a one-time stutter), then cache "
                "them again. No settings or saves are affected.")


class KdeSycocaProvider(CacheProvider):
    id = "xdg.kde-sycoca"
    name = "KDE service cache (ksycoca)"
    category = Category.DESKTOP
    safety = SafetyLevel.SAFE_CACHE

    def detect(self) -> bool:
        if not (self.ctx.which("kbuildsycoca6") or self.ctx.which("kbuildsycoca5")):
            return False
        return any(f.startswith("ksycoca")
                   for f in os.listdir(self.ctx.xdg_cache)
                   if not f.startswith(".")) if os.path.isdir(self.ctx.xdg_cache) else False

    def cache_paths(self) -> list[CachePath]:
        paths = []
        try:
            for entry in os.listdir(self.ctx.xdg_cache):
                if entry.startswith("ksycoca"):
                    paths.append(CachePath(
                        os.path.join(self.ctx.xdg_cache, entry),
                        "KDE system configuration cache (rebuilt by kbuildsycoca)",
                        SafetyLevel.SAFE_CACHE,
                    ))
        except OSError:
            pass
        return paths

    def explain(self) -> str:
        return ("Deletes KDE's service/menu cache database. KDE rebuilds it "
                "automatically via kbuildsycoca; nothing user-created is touched.")
